import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Eiji | EijiLab - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.discordapp.com/attachments/968408319343607819/995041815281537024/Untitled-1.png" />
      </Head>

      <main>
        <div className="h-screen flex items-center bg-cover" style={{backgroundImage: "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.4)), url(https://me.nsys.site/images/bg/bg15.webp)"}}>
          <div className="m-auto">
            <div className="w-[300px] sm:w-[480px] h-96 mt-[-15vh] drop-shadow-lg transition-all ease-out duration-500">
              <div className="h-2/5 bg-cover rounded-t-xl shadow-xl" style={{backgroundImage: "linear-gradient(rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.4)), url(https://devonblog.com/wp-content/uploads/2017/09/codeblauw.jpg)"}}  />
              <div className="relative bg-gray-900 rounded-b-xl shadow-xl">
                <img className="hidden sm:flex absolute top-[-50px] left-6 w-36 rounded-full shadow-md" src="https://cdn.discordapp.com/attachments/968408319343607819/995041815281537024/Untitled-1.png" alt="profile"/>
                <div className="flex justify-end p-4 sm:mb-8">
                  <div className="w-[275px]">
                    <h1 className="bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500 text-2xl font-extrabold">
                      Panit Thapwon
                    </h1>
                    <p className="text-gray-400 font-semibold">Eiji, EijiLab</p>
                  </div>
                </div>
                <div className="text-center">
                  <h1 className="text-red-300 text-lg">
                    " {/* */}
                    <span className="font-bold">Love</span> Coding &amp;
                    Me "{/* */}
                  </h1>
                  <a className="font-semibold text-rose-400 text-sm" href="https://web.facebook.com/profile.php?id=100026863880624">❤️ 28/07/48</a>
                </div>
                <div className="p-4 text-sm sm:p-6 sm:text-base">
                  <p className="text-gray-400 font-semibold mb-1">Developer</p>
                  <div className="flex mb-4">
                    <a className="bg-blue-400/20 text-blue-500 font-semibold px-2 mx-[2px] rounded transition-all ease-out duration-500 hover:bg-blue-500/20 hover:scale-110" href="https://eiji.me">Eiji</a>
                    <a className="bg-purple-400/20 text-purple-500 font-semibold px-2 mx-[2px] rounded transition-all ease-out duration-500 hover:bg-purple-500/20 hover:scale-110" href="https://eijilab.dev">EijiLab</a>
                  </div>
                  <p className="text-gray-400 font-semibold text-sm">Follow or Contact</p>
                  <div className="flex flex-wrap">
                    <a className="bg-blue-400/20 text-blue-500 font-semibold px-2 mr-[2px] mt-[4px] rounded transition-all ease-out duration-500 hover:bg-blue-500/20 hover:scale-110" href="https://web.facebook.com/profile.php?id=100026863880624">Facebook</a>
                    <a className="bg-orange-400/20 text-orange-500 font-semibold px-2 mx-[2px] mt-[4px] rounded transition-all ease-out duration-500 hover:bg-orange-500/20 hover:scale-110" href="https://www.youtube.com/channel/UCZri3ewadoOxFeoMZ_rru0A">Youtube</a>
                    <a className="bg-gray-400/20 text-gray-400 font-semibold px-2 m-[2px] mt-[4px] rounded transition-all ease-out duration-500 hover:bg-gray-500/20 hover:scale-110" href="https://github.com/DevBSys">Github</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
